Admin/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.contrib.auth.decorators import login_required


from Admin.views import *

urlpatterns = [
    path("", login_required(admin_view.as_view()), name="admin_view"),
    path("scholars_list/", (scholars_listview.as_view()), name="scholars-listview"),
    path(
        "signup_hours/",
        (signups_hoursview.as_view()),
        name="signup-hours-listview",
    ),
    path(
        "scholars_list/white_card/<int:user_id>",
        admin_scholar_white_card,
        name="admin-scholar-white-card",
    ),
    path(
        "scholars_list/profile/<int:user_id>",
        admin_scholar_list_profile,
        name="admin-scholar-profile",
    ),
    path("signup_hours/add_slots/", admin_add_slots, name="admin-add-slots"),
    path(
        "signup_hours/delete_slots/",
        admin_delete_slots_list,
        name="admin-delete-slots-list",
    ),
    path(
        "signup_hours/delete_slots/<int:id>",
        admin_delete_slots,
        name="admin-delete-slots",
    ),
    path(

        "signup_hours/edit_slots/", admin_edit_slots_list, name="admin-edit-slots-list"
    ),
    path("signup_hours/edit_slots/<int:id>", admin_edit_slots, name="admin-edit-slots"),
]

app_name = "Admin"

Scholar/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path("<int:user_id>/", login_required(scholar_view.as_view()), name="scholar_view"),
    path("<int:user_id>/profile/", view_profile, name="scholar_view_profile"),
    path("<int:user_id>/white_card/", scholar_white_card, name="scholar_white_card"),
    path(
        "<int:user_id>/profile/hours_signup",
        scholar_hours_signup,
        name="scholar_hours_signup",
    ),
    path(
        "<int:user_id>/profile/scholar_enlist_slot/<int:reg_id>/",
        scholar_enlist_slot,
        name="scholar_enlist_slot",
    ),
]

app_name = "Scholar"

tracker/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.contrib.auth.decorators import login_required

# TODO: Add if-else block here so that it redirects to admin view if user is admin, scholar view if user is scholar
@login_required
def login_redirect(request):
    # TODO: THIS IS A TEMPORARY WORKAROUND TO GET URLS WITH USER ID TO WORK - IT ALWAYS REDIRECTS TO USER 200000
    return HttpResponseRedirect(f"user_scholar/200000")
    # TODO: BELOW IS THE PROPER WAY TO REDIRECT BASED ON THE USER'S ID
    # For now, this works for login but not for any of the profile, white card, admin pages because
    # the Django project still uses Django's AuthUser model for login, not our project's custom User model
    # Once the login is configured to use the custom User model, uncomment the line below
    # return HttpResponseRedirect(f"user_scholar/{request.user.id}")


# General URLs
urlpatterns = [
    path("login_redirect", login_redirect, name="login_redirect"),
    path("admin/", admin.site.urls),
    path("", auth_views.LoginView.as_view()),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user_scholar/", include("Scholar.urls", namespace="Scholar")),
    path("user_admin/", include("Admin.urls", namespace="Admin")),
]

Scholar/models.py
from django.db import models


class User(models.Model):
    user_id = models.IntegerField(primary_key=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    user_password = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "user"

    def __str__(self):
        return "User#" + str(self.user_id)


class ServiceHourListing(models.Model):
    serv_hours_id = models.IntegerField(primary_key=True)
    serv_hours_date = models.DateField(blank=True, null=True)
    serv_hours_start_time = models.TimeField(blank=True, null=True)
    serv_hours_end_time = models.TimeField(blank=True, null=True)
    serv_hours_loc = models.CharField(max_length=255, blank=True, null=True)
    serv_hours_slot_count = models.IntegerField(blank=True, null=True)
    serv_hours_task = models.CharField(max_length=255, blank=True, null=True)
    is_rendered = models.BooleanField()

    class Meta:
        managed = False
        db_table = "service_hour_listing"

    def __str__(self):
        return str(self.serv_hours_id) + ": " + str(self.serv_hours_task)


class Scholar(models.Model):
    scholar = models.OneToOneField(User, models.DO_NOTHING, primary_key=True)
    scholar_FN = models.CharField(max_length=50, blank=True, null=True)
    scholar_LN = models.CharField(max_length=50, blank=True, null=True)
    scholar_MI = models.CharField(max_length=50, blank=True, null=True)
    hours_needed = models.IntegerField(blank=True, null=True)
    hours_rendered = models.IntegerField(blank=True, null=True)
    contact_no = models.CharField(max_length=20, blank=True, null=True)
    room_code = models.CharField(max_length=50, blank=True, null=True)
    room_name = models.CharField(max_length=100, blank=True, null=True)
    scholar_year = models.IntegerField(blank=True, null=True)
    course = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "scholar"

    def __str__(self):
        return str(self.scholar)


class Registration(models.Model):
    reg_id = models.IntegerField(primary_key=True)
    scholar = models.ForeignKey(Scholar, models.DO_NOTHING, blank=True, null=True)
    serv_hours = models.ForeignKey(
        ServiceHourListing, models.DO_NOTHING, blank=True, null=True
    )

    class Meta:
        managed = False
        db_table = "registration"

    def __str__(self):
        return str(self.serv_hours) + " assigned to: " + str(self.scholar)

Scholar/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget
from .models import Registration


class EnlistSlot(forms.Form):
    reg_id = forms.IntegerField()
    scholar_id = forms.IntegerField()
    serv_hours_id = forms.IntegerField()

    class Meta:
        managed = False
        db_table = "registration"

    def __init__(self, *args, **kwargs):
        super(EnlistSlot, self).__init__(*args, **kwargs)

Scholar/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import *
from .forms import *


class scholar_view(TemplateView):
    template_name = "scholar_view.html"

    model = User
    slug_field = "id"


def view_profile(request, user_id):
    user_details = User.objects.get(pk=user_id)
    scholar_details = Scholar.objects.get(pk=user_id)
    servHoursListing_details = ServiceHourListing.objects.all()
    return render(
        request,
        "scholar_profile.html",
        {
            "user_details": user_details,
            "scholar_details": scholar_details,
            "servHoursListing_details": servHoursListing_details,
        },
    )


def scholar_white_card(request, user_id):
    scholar_details = Scholar.objects.get(pk=user_id)
    user_details = User.objects.get(pk=user_id)
    registration = Registration.objects.select_related("serv_hours").filter(
        scholar=user_id
    )
    registration_details = Registration.objects.filter(scholar=user_id)
    service_hours = ServiceHourListing.objects.filter(registration__scholar=user_id)
    return render(
        request,
        "scholar_white_card.html",
        {
            "registration": registration,
            "user_details": user_details,
            "scholar_details": scholar_details,
            "servHoursListing_details": service_hours,
        },
    )


def scholar_hours_signup(request, user_id):
    scholar_details = Scholar.objects.get(pk=user_id)
    user_details = User.objects.get(pk=user_id)
    registration = Registration.objects.select_related("serv_hours").filter(
        scholar_id__isnull=True
    )
    service_hours = ServiceHourListing.objects.filter(registration__scholar=user_id)

    return render(
        request,
        "scholar_hours_signup.html",
        {
            "registration": registration,
            "user_details": user_details,
            "scholar_details": scholar_details,
            "servHoursListing_details": service_hours,
        },
    )


def scholar_enlist_slot(request, user_id, reg_id):
    scholar_details = Scholar.objects.get(pk=user_id)
    user_details = User.objects.get(pk=user_id)
    registration = Registration.objects.select_related("serv_hours").filter(
        scholar_id__isnull=True
    )
    if request.method == "POST":
        url = reverse("Scholar:scholar_view_profile", args=[user_id, reg_id])

        enlisted_slot = Registration.objects.get(reg_id=reg_id)
        enlisted_slot.scholar_id = user_id
        enlisted_slot.save()

        return redirect(url)
    else:
        # Handle GET request
        return render(
            request,
            "scholar_hours_signup.html",
            {
                "registration": registration,
                "user_details": user_details,
                "scholar_details": scholar_details,
            },
        )

templates/admin_add_slots.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>ADD SERVICE HOURS SLOTS</h2>
    <div class="flex-row center card">
    <form action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <input class="btn-style" type="submit" value="Add Slot">
        </div>
        <br>
    </form>
    </div>
</main>
{% endblock %}

templates/admin_delete_slots.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>DELETE SERVICE HOURS SLOTS</h2>
    <div class="flex-row center card">
    <form action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <input class="btn-style" type="submit" value="Save Changes">
        </div>
        <br>
    </form>
    </div>
</main>
{% endblock %}

templates/admin_delete_slots_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
    <h2>DELETE SERVICE HOURS SLOTS</h2>
    <div class="card">
        <div class="signup-hour-filters">
            <table>
                <tr>
                    <td><p class = "search">Search</p></td>
                    <td><textarea rows="1" cols="25"></textarea></td>
                </tr>
                <tr>
                    <td><p class="sort">Sort by</p></td>
                    <td><textarea rows="1" cols="25"></textarea></td>
                </tr>
            </table>
        </div>
        <hr class="solidline">
        <div class="card scholar-white-card">
            <table class="scholar-white-card-summary">
                <tr class="scholar-white-card-header">
                    <td>&nbsp;</td>
                    <td>DATE</td>
                    <td>TIME</td>
                    <td>BLDG</td>
                    <td>SLOT COUNT</td>
                    <td>TASKS PERFORMED</td>
                </tr>
                {% for object in serv_hours %}    
                <tr class="innerCard scholar-white-card-body signup-hour-list-override">
                    <td>{{ forloop.counter}}</td>
                    <td>{{ object.serv_hours_date }}</td>
                    <td>{{ object.serv_hours_start_time }} - {{ object.serv_hours_end_time }}</td>
                    <td>{{ object.serv_hours_loc }}</td>
                    <td>{{ object.serv_hours_slot_count }}</td>
                    <td>{{ object.serv_hours_task }}</td>
                    <td><a href="{% url 'Admin:admin-delete-slots' object.serv_hours_id%}">Delete</a></td>
                </tr>
                {% endfor %}
            </table> 
        </div>
    </div>
</main>
{% endblock %}

templates/admin_edit_slots.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>EDIT SERVICE HOURS SLOTS</h2>
    <div class="flex-row center card">
    <form action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <input class="btn-style" type="submit" value="Save Changes">
        </div>
        <br>
    </form>
    </div>
</main>
{% endblock %}

templates/admin_edit_slots_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
    <h2>EDIT SERVICE HOURS SLOTS</h2>
    <div class="card">
        <div class="signup-hour-filters">
            <table>
                <tr>
                    <td><p class = "search">Search</p></td>
                    <td><textarea rows="1" cols="25"></textarea></td>
                </tr>
                <tr>
                    <td><p class="sort">Sort by</p></td>
                    <td><textarea rows="1" cols="25"></textarea></td>
                </tr>
            </table>
        </div>
        <hr class="solidline">
        <div class="card scholar-white-card">
            <table class="scholar-white-card-summary">
                <tr class="scholar-white-card-header">
                    <td>&nbsp;</td>
                    <td>DATE</td>
                    <td>TIME</td>
                    <td>BLDG</td>
                    <td>SLOT COUNT</td>
                    <td>TASKS PERFORMED</td>
                </tr>
                {% for object in serv_hours %}    
                <tr class="innerCard scholar-white-card-body signup-hour-list-override">
                    <td>{{ forloop.counter}}</td>
                    <td>{{ object.serv_hours_date }}</td>
                    <td>{{ object.serv_hours_start_time }} - {{ object.serv_hours_end_time }}</td>
                    <td>{{ object.serv_hours_loc }}</td>
                    <td>{{ object.serv_hours_slot_count }}</td>
                    <td>{{ object.serv_hours_task }}</td>
                    <td><a href="{% url 'Admin:admin-edit-slots' object.serv_hours_id%}">Edit</a></td>
                </tr>
                {% endfor %}
            </table> 
        </div>
    </div>
</main>
{% endblock %}

templates/admin_scholar_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dorm Scholars{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2 class="headerColor">LIST OF DORM SCHOLARS</h2>
<div class="scholar_list-filter">
    <div><p class = "search">Search  <textarea rows="1" cols="50"></textarea></p> </div>
    <div><p class="sort">Sort by  <textarea rows="1" cols="50"></textarea></p> </div>
</div>

<div class="card">
    <table id="scholar_list-table">
        {% for object in object_list%}
            <tr class="innerCard">
                <td><span id="lastName">{{ object.scholar_LN }}</span>, {{ object.scholar_FN }} {{ object.scholar_MI }}.</td>
                <td>{{ object.room_code }}</td>
                <td><a href="profile/{{ object.scholar.user_id }}">View Profile</a></td>
                <td><a href="white_card/{{ object.scholar.user_id }}">View White Card</a></td>
            </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        <ul class="step-links">
            {% if page_obj.has_previous %}
                <li><a href="?page=1">&lt;&lt;</a></li>
                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% else %}
                <li><a href="">&lt;&lt;</a></li>
                <li><a href="">&lt;</a></li>
            {% endif %}
            <li id="page_number"><span>{{ page_obj.number|stringformat:"02d" }}</span></li>

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;&gt;</a></li>
            {% else %}
                <li><a href="">&gt;</a></li>
                <li><a href="">&gt;&gt;</a></li>
            {% endif %}
        </ul>
    </div>
</div>








</main>
{% endblock %}

templates/admin_scholar_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br> Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>Profile</h2>
<div class="flex-row">
    <div class="card flex-3-2 profile-details">
        <table>
            <tr class="align-left">
                <th>Name</th>
                <td><span>{{ scholar_details.scholar_LN }}</span>, {{ scholar_details.scholar_FN }} {{ scholar_details.scholar_MI}}. </td>
            </tr>
            <tr  class="align-left">
                <th>ID Number</th>
                <td>{{ scholar_details.scholar.user_id }}</td>
            </tr>
            <tr  class="align-left">
                <th>Yr. & Course Code</th>
                <td>{{ scholar_details.scholar_year }} {{ scholar_details.course }}</td>
            </tr>
            <tr  class="align-left">
                <th>OBF Email</th>
                <td>{{ scholar_details.scholar.email }}</td>
            </tr>
            <tr  class="align-left">
                <th>Bldg. & Room No.</th>
                <td>{{ scholar_details.room_code }}</td>
            </tr>
            <tr  class="align-left">
                <th>Contact No.</th>
                <td>{{ scholar_details.contact_no }}</td>
            </tr>
        </table>
        <div class="profile-edit-button"><button>EDIT PROFILE</button></div>
    </div>
    <div class="card flex profile-deloading flex-column">
        <h3>Deloading Request Status:</h3>
        <p class="flex">Not submitted</p>
        <div class="deloading-request-button"><button><a href="">VIEW REQUEST</a></button></div>
    </div>
</div>

<div class="card profile-signup">
    <h2>Signup</h2>
    <p>Scholar has not signed up<br>for dorm service hours yet.</p>
    <div><button><a href="">EDIT</a></button></div>
</div>
</main>
{% endblock %}

templates/admin_signups_hours.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Signups Hours{% endblock %}

{% block content %}
<header>
    <p><a href="{% url 'Admin:scholars-listview' %}">LIST OF<br>DORM SCHOLARS</a></p>
    <p><a href="{% url 'Admin:signup-hours-listview' %}">Signups<br>Hours</a></p>
    <a href="{% url 'Admin:admin_view' %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Requests</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>SIGNUPS HOURS</h2>
<div class="card">
    <div class="signup-hour-filters">
        <table>
            <tr>
                <td><p class = "search">Search</p></td>
                <td><textarea rows="1" cols="25"></textarea></td>
            </tr>
            <tr>
                <td><p class="sort">Sort by</p></td>
                <td><textarea rows="1" cols="25"></textarea></td>
            </tr>
        </table>
        <table>
            <tr>
                <td><button class="signup-hour-btn" onclick="location.href='add_slots/';">ADD SLOT</button></td>
                <td><button class="signup-hour-btn">ADD MULTIPLE SLOTS</button></td>
            </tr>
            <tr>
                <td><button class="signup-hour-btn" onclick="location.href='delete_slots/';">DELETE SLOT</button></td>
                <td><button class="signup-hour-btn">DELETE MULTIPLE SLOTS</button></td>
            </tr>
            <tr>
                <td></td>
                <td><button class="signup-hour-btn" onclick="location.href='edit_slots/';">EDIT SLOTS</button></td>
            </tr>
        </table>
    </div>
    <hr class="solidline">
    <div class="card scholar-white-card">
        <table class="scholar-white-card-summary">
            <tr class="scholar-white-card-header">
                <td>&nbsp;</td>
                <td>DATE</td>
                <td>TIME</td>
                <td>BLDG</td>
                <td>SLOT COUNT</td>
                <td>TASKS PERFORMED</td>
            </tr>
            {% for object in object_list %}    
            <tr class="innerCard scholar-white-card-body signup-hour-list-override">
                <td>{{ forloop.counter}}</td>
                <td>{{ object.serv_hours_date }}</td>
                <td>{{ object.serv_hours_start_time }} - {{ object.serv_hours_end_time }}</td>
                <td>{{ object.serv_hours_loc }}</td>
                <td>{{ object.serv_hours_slot_count }}</td>
                <td>{{ object.serv_hours_task }}</td>
            </tr>
            {% endfor %}
        </table> 
    </div>

    <div class="pagination">
        <ul class="step-links">
            {% if page_obj.has_previous %}
                <li><a href="?page=1">&lt;&lt;</a></li>
                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% else %}
                <li><a href="">&lt;&lt;</a></li>
                <li><a href="">&lt;</a></li>
            {% endif %}
            <li id="page_number"><span>{{ page_obj.number|stringformat:"02d" }}</span></li>

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;&gt;</a></li>
            {% else %}
                <li><a href="">&gt;</a></li>
                <li><a href="">&gt;&gt;</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</main>
{% endblock %}

templates/admin_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<header>
    <img class="logo" src="{% static 'logo.png' %}">
</header>

<main>
<div class="flex-row user-info">
    <p>{{ user.username }}</p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
</div>

<div class="flex-row center homepage-card-div">
    <div class="card homepage-card"><p><a href="{% url 'Admin:scholars-listview' %}">Dorm Scholars</a></p></div>
    <div class="card homepage-card"><p><a href="{% url 'Admin:signup-hours-listview' %}">Signups Hours</a></p></div>
    <div class="card homepage-card"><p><a href="">Requests</a></p></div>
    <div class="card homepage-card"><p><a href="">Contact</a></p></div>
</div>
</main>
<br><br>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en-us">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--<link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">-->
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
  <title>{% block title %}Dorm Service Hours Tracker{% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <footer>
      <p>© 2022 GoDaddy</p>
    </footer>
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<header>
    <img class="logo" src="{% static 'logo.png' %}">
</header>

<main>
<div class="flex-row user-info">
    <p>{{ user.username }}</p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
</div>

<div class="flex-row center homepage-card-div">
    <div class="card homepage-card"><p class="center"><a href="{% url 'profile' %}">Profile</a></p></div>
    <div class="card homepage-card"><p class="center"><a href="{% url 'white_card' %}">White Card</a></p></div>
    <div class="card homepage-card"><p class="center"><a href="">Swap Hours</a></p></div>
    <div class="card homepage-card"><p class="center"><a href="">Contact</a></p></div>
</div>
</main>
{% endblock %}

templates/scholar_hours_signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Scholar's White Card{% endblock %}

{% block content %}

<header>
    <p><a href="{% url 'Scholar:scholar_view_profile' user_id=user_details.user_id %}">Profile</a></p>
    <p><a href="{% url 'Scholar:scholar_white_card' user_id=user_details.user_id %}">White Card</a></p>
    <a href="{% url 'Scholar:scholar_view' user_id=user_details.user_id %}" ><img class="logo" src="{% static 'logo.png' %}"></a>
    <p><a href="">Swap<br>Hours</a></p>
    <p><a href="">Contact</a></p>
</header>

<main>
<h2>SIGNUP FOR HOURS</h2>

<div>
    {% for listing in registration %}
        <div class="card profile-signup">
        {{ listing.serv_hours.serv_hours_date }} <br>
        {{ listing.serv_hours.serv_hours_start_time }} <br>
        {{ listing.serv_hours.serv_hours_end_time }} <br>
        {{ listing.serv_hours.serv_hours_loc }} <br><br>

        <form method="post">
            {% csrf_token %}
            <div><button type="submit"><a href="{% url 'Scholar:scholar_enlist_slot' user_id=user_details.user_id reg_id=listing.reg_id %}">Enlist</a></button></div>
        </form>
    </div>
    {% endfor %}
</div>

</main>

{% endblock %}